# Generated by Django 3.2.9 on 2021-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_inventory_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='型号')),
                ('note', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'db_table': 'type',
            },
        ),
    ]
