# Generated by Django 3.2.9 on 2021-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=50, verbose_name='供货单号')),
                ('supplier', models.CharField(max_length=25, verbose_name='供货商')),
                ('supply_time', models.CharField(max_length=15, verbose_name='供货时间')),
                ('type', models.CharField(max_length=10, verbose_name='供货类型')),
                ('number', models.IntegerField(default=0, verbose_name='供货数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='供货单价')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='供货总价')),
                ('note', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'db_table': 'supply',
            },
        ),
    ]
