# Generated by Django 3.2.9 on 2021-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
    ]
