# Generated by Django 3.2.9 on 2021-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0006_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='交易人')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('tradingitems', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('payamount', models.IntegerField(verbose_name='支付金额')),
                ('paymethods', models.CharField(max_length=10, verbose_name='支付方式')),
                ('arrearamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='拖欠金额')),
                ('date', models.CharField(max_length=15, verbose_name='供货时间')),
            ],
            options={
                'db_table': 'sell',
            },
        ),
    ]
