# Generated by Django 3.2.9 on 2021-12-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10, verbose_name='产品')),
                ('information', models.TextField(verbose_name='产品介绍')),
                ('picture', models.ImageField(upload_to='')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('alter_date', models.DateField(auto_now=True, verbose_name='修改日期')),
                ('release', models.CharField(default='否', max_length=1, verbose_name='是否已发布')),
            ],
        ),
    ]
