# Generated by Django 3.2.9 on 2021-12-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_productinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productinfo',
            table='productshow',
        ),
    ]
