# Generated by Django 3.2.9 on 2021-12-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_alter_productinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='picture',
            field=models.ImageField(upload_to='picture_show'),
        ),
    ]
