# Generated by Django 3.2.9 on 2021-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_alter_productinfo_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pic_height',
            field=models.IntegerField(null=True, verbose_name='图片高'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pic_width',
            field=models.IntegerField(null=True, verbose_name='图片宽'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='产品介绍'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='picture',
            field=models.ImageField(blank=True, height_field='pic_height', null=True, upload_to='picture_show', verbose_name='图片', width_field='pic_width'),
        ),
    ]
