# Generated by Django 3.2.9 on 2021-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='型号')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('mobile', models.CharField(default='', max_length=15, verbose_name='联系方式')),
                ('date', models.CharField(default='', max_length=15, verbose_name='预期前往时间')),
                ('note', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
